language: ruby
rvm:
  - 1.9.2
install: true
before_install: bash -e ./travis/before-rvm-test.sh
script: bash ./travis/rvm-test.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
      - "irc.freenode.org#rvm"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
